name = "SXTMerger"
uuid = "05795ded-2e6b-4fe1-8ca7-69dda6a83a16"
authors = ["Gulab Dewangan <gulabd@iucaa.in>"]
version = "1.1.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"

[compat]
DataFrames = "1.5"
FITSIO = "0.17"
julia = "1.9"
